---

- name: Check existence of couchdb systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ couchdb_identifier }}.service"
  register: couchdb_service_stat

- when: couchdb_service_stat.stat.exists | bool
  block:
    - name: Ensure couchdb service is stopped
      ansible.builtin.service:
        name: "{{ couchdb_identifier }}.service"
        state: stopped
        daemon_reload: true
    - name: Ensure couchdb service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ couchdb_identifier }}.service"
        state: absent

- name: Ensure couchdb base path is files deleted
  ansible.builtin.file:
    path: "{{ couchdb_base_path }}"
    state: absent
